// LOCAL HOST
### Get all contacts
GET http://localhost:3000/contacts


### Get contact by Id
GET http://localhost:3000/contacts/67951ce02339fa1d0580b292

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "name": "Armando Mendoza",
    "phone": "333-456-7890",
    "email": "armnado@mendoza.com",
    "address": "123 Main St, Springfield, USA"
}

### Put contact
PUT http://localhost:3000/contacts/67951e1a7b2a5a040a1700ab HTTP/1.1
Content-Type: application/json

{
    "name": "Oscar Reyes",
    "phone": "424-855-6526",
    "email": "oscar.reyes@hotmail.com",
    "address": "789 Chestnut Pl, North Shelbyville, USA"
}


### DELETE Contact
DELETE http://localhost:3000/contacts/67951e1a7b2a5a040a1700ab HTTP/1.1